### ISSUE TITLE
Larger size column offsets can't be zero when a smaller size offset is greater than zero

### ISSUE THREAD

**Issue by Shrinks99** [electerious/basicGrid#12]
Columns with `small-offset-x` and `large-offset-0` or `medium-offset-0` don't seem to work.  The zeroed out offsets (if set to greater than zero it functions as expected) just inherit the value of the `small-offset-x` for the larger breakpoints.  This seems to be because of the way the `margin-left` value is calculated as a percentage.

~~Adding this as an override for those two classes specifically seems to fix the issue:~~ Never mind this seems to override the small offset at the small size. :(
```css
.large-offset-0, .medium-offset-0 {
	margin-left: 0 !important;
}
```
